### ISSUE TITLE
Segmentation Fault with soon to expire password

### ISSUE THREAD

**Issue by bruceceng** [Rush/node-authenticate-pam#22]
Using pam with kerberos  (krb5) to authenticate on Windows domain. When password is close to expiration date (on Windows it says your password will expire in x days), pam crashes with segmentation fault. I believe it may be do to how conversation callback is being handled. Maybe pam tries to free pointer that was never malloc'd?

**Comment by Rush** [comment]
Just wanna confirm, are you running latest version with this commit? https://github.com/Rush/node-authenticate-pam/commit/f5f1c64b35023ef685d3fd23e25a66d0da2890f9

**Comment by bruceceng** [comment]
I think that's it. I've been waiting over a month for my password to get old again so I could reproduce the problem so I must have missed this. Thanks.

**Comment by grkblood13** [comment]
This problem still exists. To recreate on linux:

sudo useradd tester1
sudo passwd tester1
chage -M 1 tester1
node test.js tester1 password

output: program takes longer than expected and returns with "Login failure: Authentication failure"

**Comment by grkblood13** [comment]
So, this issue IS still present. To reproduce do what I said above, but run the test program "test.js" as a non-root user.

If you run the program as root it will work. If you run it as a regular user it won't.
